# Generated by Django 5.2 on 2025-04-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_quantity_car_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
