# Generated by Django 5.2 on 2025-04-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=10),
        ),
    ]
